project_name: glitchtipctl

builds:
  - id: my_build
    main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md

changelog:
  use: git

release:
  github:
    owner: Nanyte25
    name: glitchtipctl
    token: ${{ secrets.GITHUB_TOKEN }}