name: Release

on:
  push:
    tags:
      - 'v1.0.3'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Latest version

      - name: Set up Go
        uses: actions/setup-go@v4  # Latest version
        with:
          go-version: '1.21'

      - name: Install GoReleaser
        run: |
          curl -sL https://git.io/goreleaser | bash

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --clean

