name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Updated to use the latest version of checkout action
      - name: Checkout code
        uses: actions/checkout@v4

      # Updated to use the latest version of setup-go action
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      # Install GoReleaser (latest stable version)
      - name: Install GoReleaser
        run: curl -sL https://git.io/goreleaser | bash

      # Run GoReleaser
      - name: Run GoReleaser
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



